# -*- coding: utf-8 -*-
"""Dashboard_Interaktif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVcNzqOR8EJb1Wu5-LFGfUZkj9MNG1N7
"""

!pip install plotly pandas openpyxl -q

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
from datetime import datetime

from google.colab import files
print("Silakan upload file Coffe_sales.pdf atau CSV Anda:")
uploaded = files.upload()

data = {
    'hour_of_day': [],
    'cash_type': [],
    'money': [],
    'coffee_name': [],
    'Time_of_Day': [],
    'Weekday': [],
    'Month_name': [],
    'Date': []
}

def load_coffee_data():
    """
    Fungsi untuk memuat data penjualan kopi
    Sesuaikan dengan format file
    """
    try:
        df = pd.read_csv(list(uploaded.keys())[0])
    except:
        print("File tidak bisa dibaca sebagai CSV.")
        # Membuat sample data
        df = pd.DataFrame({
            'hour_of_day': np.random.randint(7, 22, 500),
            'cash_type': np.random.choice(['card', 'cash'], 500),
            'money': np.random.uniform(20, 40, 500),
            'coffee_name': np.random.choice(['Latte', 'Americano', 'Cappuccino', 'Espresso', 'Hot Chocolate'], 500),
            'Time_of_Day': np.random.choice(['Morning', 'Afternoon', 'Night'], 500),
            'Weekday': np.random.choice(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 500),
            'Month_name': np.random.choice(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], 500),
            'Date': pd.date_range('2024-01-01', periods=500, freq='H')
        })

    return df

# Load data
df = load_coffee_data()

# Konversi kolom Date jika ada
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print("Data berhasil dimuat!")
print(f"Jumlah transaksi: {len(df)}")
print("\nPreview data:")
print(df.head())

# ============================================
# DASHBOARD VISUALIZATIONS
# ============================================

# 1. Penjualan berdasarkan Jenis Kopi
fig1 = px.bar(df.groupby('coffee_name')['money'].sum().reset_index().sort_values('money', ascending=False),
              x='coffee_name', y='money',
              title='Total Penjualan per Jenis Kopi',
              labels={'coffee_name': 'Jenis Kopi', 'money': 'Total Penjualan (IDR)'},
              color='money',
              color_continuous_scale='Viridis')
fig1.update_layout(showlegend=False, height=400)
fig1.show()

# 2. Penjualan berdasarkan Jam
hourly_sales = df.groupby('hour_of_day')['money'].agg(['sum', 'count']).reset_index()
fig2 = make_subplots(specs=[[{"secondary_y": True}]])
fig2.add_trace(
    go.Bar(x=hourly_sales['hour_of_day'], y=hourly_sales['sum'],
           name='Total Penjualan', marker_color='lightblue'),
    secondary_y=False
)
fig2.add_trace(
    go.Scatter(x=hourly_sales['hour_of_day'], y=hourly_sales['count'],
               name='Jumlah Transaksi', mode='lines+markers',
               marker=dict(size=8, color='red')),
    secondary_y=True
)
fig2.update_layout(title='Penjualan per Jam dalam Sehari',
                   xaxis_title='Jam',
                   height=400)
fig2.update_yaxes(title_text="Total Penjualan (IDR)", secondary_y=False)
fig2.update_yaxes(title_text="Jumlah Transaksi", secondary_y=True)
fig2.show()

# 3. Penjualan berdasarkan Hari dalam Seminggu
day_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
daily_sales = df.groupby('Weekday')['money'].sum().reindex(day_order).reset_index()
fig3 = px.line(daily_sales, x='Weekday', y='money',
               title='Penjualan per Hari dalam Seminggu',
               labels={'Weekday': 'Hari', 'money': 'Total Penjualan (IDR)'},
               markers=True)
fig3.update_traces(line_color='green', line_width=3, marker=dict(size=10))
fig3.update_layout(height=400)
fig3.show()

# 4. Distribusi Metode Pembayaran
payment_dist = df.groupby('cash_type')['money'].sum().reset_index()
fig4 = px.pie(payment_dist, values='money', names='cash_type',
              title='Distribusi Metode Pembayaran',
              color_discrete_sequence=['#FF6B6B', '#4ECDC4'])
fig4.update_traces(textposition='inside', textinfo='percent+label')
fig4.update_layout(height=400)
fig4.show()

# 5. Penjualan berdasarkan Waktu Hari (Morning/Afternoon/Night)
time_sales = df.groupby('Time_of_Day')['money'].sum().reset_index()
fig5 = px.bar(time_sales, x='Time_of_Day', y='money',
              title='Penjualan berdasarkan Waktu Hari',
              labels={'Time_of_Day': 'Waktu', 'money': 'Total Penjualan (IDR)'},
              color='Time_of_Day',
              color_discrete_map={'Morning': '#FFD93D', 'Afternoon': '#FF6B6B', 'Night': '#6C5CE7'})
fig5.update_layout(showlegend=False, height=400)
fig5.show()

# 6. Heatmap: Penjualan per Jam dan Hari
heatmap_data = df.pivot_table(values='money', index='hour_of_day',
                               columns='Weekday', aggfunc='sum', fill_value=0)
heatmap_data = heatmap_data[day_order]  # Reorder columns
fig6 = px.imshow(heatmap_data,
                 labels=dict(x="Hari", y="Jam", color="Penjualan (IDR)"),
                 title="Heatmap: Penjualan per Jam dan Hari",
                 color_continuous_scale='RdYlGn',
                 aspect='auto')
fig6.update_layout(height=500)
fig6.show()

# 7. Top 5 Kopi Terlaris
top_coffee = df.groupby('coffee_name').agg({
    'money': 'sum',
    'coffee_name': 'count'
}).rename(columns={'coffee_name': 'transactions'}).sort_values('money', ascending=False).head(5)
fig7 = go.Figure()
fig7.add_trace(go.Bar(
    x=top_coffee.index,
    y=top_coffee['money'],
    text=top_coffee['transactions'],
    texttemplate='%{text} transaksi',
    textposition='outside',
    marker_color='indianred'
))
fig7.update_layout(title='Top 5 Kopi Terlaris',
                   xaxis_title='Jenis Kopi',
                   yaxis_title='Total Penjualan (IDR)',
                   height=400)
fig7.show()

# 8. Tren Penjualan Bulanan
if 'Date' in df.columns and pd.api.types.is_datetime64_any_dtype(df['Date']):
    monthly_trend = df.groupby(df['Date'].dt.to_period('M'))['money'].sum().reset_index()
    monthly_trend['Date'] = monthly_trend['Date'].astype(str)
    fig8 = px.area(monthly_trend, x='Date', y='money',
                   title='Tren Penjualan Bulanan',
                   labels={'Date': 'Bulan', 'money': 'Total Penjualan (IDR)'})
    fig8.update_traces(line_color='#FF6B6B', fillcolor='rgba(255, 107, 107, 0.3)')
    fig8.update_layout(height=400)
    fig8.show()

# 9. Dashboard Summary dengan KPI
total_sales = df['money'].sum()
total_transactions = len(df)
avg_transaction = df['money'].mean()
top_coffee_name = df.groupby('coffee_name')['money'].sum().idxmax()

# Create KPI dashboard
fig9 = go.Figure()

fig9.add_trace(go.Indicator(
    mode="number",
    value=total_sales,
    title={'text': "Total Penjualan<br>(IDR)"},
    domain={'x': [0, 0.25], 'y': [0.5, 1]},
    number={'prefix': "Rp ", 'valueformat': ",.0f"}
))

fig9.add_trace(go.Indicator(
    mode="number",
    value=total_transactions,
    title={'text': "Total Transaksi"},
    domain={'x': [0.25, 0.5], 'y': [0.5, 1]},
    number={'valueformat': ","}
))

fig9.add_trace(go.Indicator(
    mode="number",
    value=avg_transaction,
    title={'text': "Rata-rata Transaksi<br>(IDR)"},
    domain={'x': [0.5, 0.75], 'y': [0.5, 1]},
    number={'prefix': "Rp ", 'valueformat': ",.0f"}
))

fig9.add_trace(go.Indicator(
    mode="number+delta",
    value=df[df['coffee_name'] == top_coffee_name]['money'].sum(),
    title={'text': f"Penjualan {top_coffee_name}"},
    domain={'x': [0.75, 1], 'y': [0.5, 1]},
    number={'prefix': "Rp ", 'valueformat': ",.0f"}
))

fig9.update_layout(
    title={'text': "Dashboard KPI - Penjualan Kopi", 'x': 0.5, 'xanchor': 'center'},
    height=300
)
fig9.show()

# 10. Perbandingan Penjualan per Kopi dan Metode Pembayaran
comparison = df.groupby(['coffee_name', 'cash_type'])['money'].sum().reset_index()
fig10 = px.bar(comparison, x='coffee_name', y='money', color='cash_type',
               title='Perbandingan Penjualan per Kopi dan Metode Pembayaran',
               labels={'coffee_name': 'Jenis Kopi', 'money': 'Total Penjualan (IDR)', 'cash_type': 'Metode'},
               barmode='group')
fig10.update_layout(height=400)
fig10.show()

print("\n Dashboard berhasil dibuat!")
print(f" Total visualisasi: 10 grafik interaktif")