# -*- coding: utf-8 -*-
"""Visualisasi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4Qd5jooKf9RsZZ8W2l_S1hKYfaIDO6Y
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Coffe_sales.csv')
df.head()

#   BAR CHART

bar_data = df.groupby('coffee_name')['money'].sum().sort_values()

plt.figure(figsize=(12,6))
bar_data.plot(kind='bar')
plt.title("Total Money per Coffee Type")
plt.xlabel("Coffee Name")
plt.ylabel("Total Money")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')

from google.colab import files
uploaded = files.upload()


df = pd.read_csv('Coffe_sales.csv')
df.head()

#  LINE CHART

# Convert kolom Date ke datetime
df['Date'] = pd.to_datetime(df['Date'])

# Aggregate pendapatan per hari
daily_sales = df.groupby('Date')['money'].sum()

plt.figure(figsize=(14,6))
plt.plot(daily_sales.index, daily_sales.values, marker='o')
plt.title(" Daily Revenue Over Time ")
plt.xlabel("Date")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')

from google.colab import files
uploaded = files.upload()


df = pd.read_csv('Coffe_sales.csv')
df.head()

#  SCATTER PLOT

# Hitung rata-rata penjualan per jam
hourly_avg = df.groupby('hour_of_day')['money'].mean()

plt.figure(figsize=(10,6))
plt.scatter(hourly_avg.index, hourly_avg.values, s=80)
plt.plot(hourly_avg.index, hourly_avg.values)
plt.title("Average Revenue per Hour (Scatter Version)")
plt.xlabel("Hour of Day")
plt.ylabel("Average Money")
plt.grid(True)
plt.tight_layout()
plt.show()